# Generated by Django 5.0.7 on 2024-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="exam_time",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
