# Generated by Django 5.0.7 on 2024-08-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_exam_exam_time_alter_assignment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                default="Not started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
