# Generated by Django 5.0.7 on 2024-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_assignment_status_alter_exam_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not started", "Not started"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                default="Not started",
                max_length=20,
                null=True,
            ),
        ),
    ]
