# Generated by Django 5.0.7 on 2024-08-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_assignment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
    ]
