# Generated by Django 5.0.7 on 2024-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="due_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
