# Generated by Django 5.0.7 on 2024-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_assignment_due_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="due_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
